//! Cross-implementation conformance: this Zig port against the SDK's oracle.
//!
//! The vector is GENERATED by `plexus-sdk-ts/tools/gen-derivation-vector.mjs` and
//! vendored here verbatim. Its provenance and sha256 are in `vectors/README.md`.
//! Nothing in this file invents an expected value — every assertion reads from
//! the vector, so a drifting port fails rather than a drifting test passing.

const std = @import("std");
const derive = @import("derive");

const GOLDEN = @embedFile("golden");

const Vector = struct {
    parsed: std.json.Parsed(std.json.Value),

    fn load(allocator: std.mem.Allocator) !Vector {
        return .{ .parsed = try std.json.parseFromSlice(
            std.json.Value,
            allocator,
            GOLDEN,
            .{},
        ) };
    }
    fn deinit(self: *Vector) void {
        self.parsed.deinit();
    }
    fn root(self: Vector) std.json.Value {
        return self.parsed.value;
    }
};

fn obj(v: std.json.Value, key: []const u8) std.json.Value {
    return v.object.get(key).?;
}
fn str(v: std.json.Value, key: []const u8) []const u8 {
    return obj(v, key).string;
}
fn int(v: std.json.Value, key: []const u8) i64 {
    return obj(v, key).integer;
}
fn arr(v: std.json.Value, key: []const u8) []std.json.Value {
    return obj(v, key).array.items;
}

// ── constants ────────────────────────────────────────────────────────────────

test "constants: PBKDF2 parameters match the vector" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const p = obj(obj(v.root(), "constants"), "pbkdf2");
    try std.testing.expectEqual(@as(i64, derive.pbkdf2_iterations), int(p, "iterations"));
    try std.testing.expectEqual(@as(i64, @intCast(derive.pbkdf2_key_length)), int(p, "keyLength"));
    try std.testing.expectEqualStrings("sha512", str(p, "digest"));
}

// ── root keys ────────────────────────────────────────────────────────────────

test "rootKeys: every (email, salt) pair reproduces the oracle's root" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const cases = arr(v.root(), "rootKeys");
    try std.testing.expect(cases.len >= 3);
    for (cases) |c| {
        const key = try derive.deriveRootKey(str(c, "email"), str(c, "salt"));
        try std.testing.expectEqualStrings(str(c, "privHex"), &derive.privHex(key));
        try std.testing.expectEqualStrings(str(c, "pubHex"), &(try derive.pubHex(key)));
    }
}

test "rootKeys: a different salt yields a different universe" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();
    const cases = arr(v.root(), "rootKeys");
    // Same email, different salt — the vector's first two cases.
    try std.testing.expectEqualStrings(str(cases[0], "email"), str(cases[1], "email"));
    try std.testing.expect(!std.mem.eql(u8, str(cases[0], "privHex"), str(cases[1], "privHex")));
}

// ── invoice numbers ──────────────────────────────────────────────────────────

test "invoiceNumbers: every case renders exactly, including the colon collision" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    var saw_colon_case = false;
    for (arr(v.root(), "invoiceNumbers")) |c| {
        const resource_id = str(c, "resourceId");
        const flag: u64 = @intCast(int(c, "domainFlag"));
        const index: u64 = @intCast(int(c, "childIndex"));

        const got = try derive.buildInvoiceNumber(a, resource_id, flag, index);
        defer a.free(got);
        try std.testing.expectEqualStrings(str(c, "invoiceNumber"), got);

        // The cert-field encoding is HEX and unpadded, unlike the decimal the
        // invoice uses. Both are pinned, because confusing them is silent.
        const enc = try derive.encodeDomainFlag(a, flag);
        defer a.free(enc);
        try std.testing.expectEqualStrings(str(c, "domainFlagCertEncoding"), enc);

        if (std.mem.indexOfScalar(u8, resource_id, ':') != null) saw_colon_case = true;
    }
    // The vector deliberately carries a resourceId containing a colon. If it
    // ever stops doing so, this port's reproduction of that ambiguity is no
    // longer covered and the assumption should be revisited.
    try std.testing.expect(saw_colon_case);
}

test "invoiceNumbers: invalid inputs are refused" {
    const a = std.testing.allocator;
    try std.testing.expectError(
        derive.Error.EmptyResourceId,
        derive.buildInvoiceNumber(a, "", 2, 0),
    );
    try std.testing.expectError(
        derive.Error.InvalidDomainFlag,
        derive.buildInvoiceNumber(a, "inbox", 0, 0),
    );
    try std.testing.expectError(
        derive.Error.InvalidDomainFlag,
        derive.buildInvoiceNumber(a, "inbox", 0x1_0000_0000, 0),
    );
}

// ── plexus-kdf-v1 ────────────────────────────────────────────────────────────

test "plexus-kdf-v1: every case matches the oracle" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const root_key = try derive.deriveRootKey(
        str(universe, "rootEmail"),
        str(universe, "rootSalt"),
    );

    const v1 = obj(obj(v.root(), "kdf"), "plexus-kdf-v1");
    const cases = v1.object.get("cases").?.array.items;
    try std.testing.expect(cases.len >= 2);
    for (cases) |c| {
        const child = try derive.deriveChildV1(root_key, str(c, "invoiceNumber"));
        try std.testing.expectEqualStrings(str(c, "privHex"), &derive.privHex(child));
        try std.testing.expectEqualStrings(str(c, "pubHex"), &(try derive.pubHex(child)));
    }
}

test "plexus-kdf-v1: self-derivation, not an external counterparty" {
    // Guards the exact confusion with host.deriveLeaf: derive the same invoice
    // against a DIFFERENT counterparty and it must not produce the vector's key.
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const root_key = try derive.deriveRootKey(
        str(universe, "rootEmail"),
        str(universe, "rootSalt"),
    );
    const cases = obj(obj(v.root(), "kdf"), "plexus-kdf-v1").object.get("cases").?.array.items;
    const invoice = str(cases[0], "invoiceNumber");

    const stranger = try derive.deriveRootKey("stranger@example.test", "other-salt");
    const wrong = try root_key.deriveChild(try stranger.publicKey(), invoice);
    try std.testing.expect(!std.mem.eql(u8, str(cases[0], "privHex"), &derive.privHex(wrong)));
}

// ── paths ────────────────────────────────────────────────────────────────────

test "derivationPaths: every path walks to the oracle's key" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const email = str(universe, "rootEmail");
    const salt = str(universe, "rootSalt");

    const paths = arr(v.root(), "derivationPaths");
    try std.testing.expect(paths.len >= 3);
    for (paths) |p| {
        const key = try derive.derivePrivateKeyAtPath(email, salt, str(p, "path"));
        try std.testing.expectEqualStrings(str(p, "privHex"), &derive.privHex(key));
        try std.testing.expectEqualStrings(str(p, "pubHex"), &(try derive.pubHex(key)));
    }
}

test "derivationPaths: malformed paths are refused" {
    try std.testing.expectError(
        derive.Error.PathMustBeginAtRoot,
        derive.derivePrivateKeyAtPath("e", "s", "inbox:2:0"),
    );
    try std.testing.expectError(
        derive.Error.EmptyPathSegment,
        derive.derivePrivateKeyAtPath("e", "s", "root//inbox:2:0"),
    );
    try std.testing.expectError(
        derive.Error.EmptyPath,
        derive.derivePrivateKeyAtPath("e", "s", ""),
    );
}

// ── child counter sequence ───────────────────────────────────────────────────

test "childCounterSequence: replaying the oracle's calls reproduces every index and key" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const email = str(universe, "rootEmail");
    const salt = str(universe, "rootSalt");
    const root_key = try derive.deriveRootKey(email, salt);

    const seq = obj(v.root(), "childCounterSequence");
    const root_cert_id = str(seq, "rootCertId");
    const steps = seq.object.get("steps").?.array.items;
    try std.testing.expect(steps.len >= 5);

    var counters = derive.ChildCounters.init(a);
    defer counters.deinit();

    for (steps) |s| {
        const resource_id = str(s, "resourceId");
        const flag: u64 = @intCast(int(s, "domainFlag"));

        // The index is ALLOCATED, not read from the vector — that is the point.
        const index = try counters.next(root_cert_id, resource_id, flag);
        try std.testing.expectEqual(@as(u64, @intCast(int(s, "childIndex"))), index);

        const invoice = try derive.buildInvoiceNumber(a, resource_id, flag, index);
        defer a.free(invoice);
        try std.testing.expectEqualStrings(str(s, "invoiceNumber"), invoice);

        const path = try std.fmt.allocPrint(a, "root/{s}", .{invoice});
        defer a.free(path);
        try std.testing.expectEqualStrings(str(s, "derivationPath"), path);

        const child = try derive.deriveChildV1(root_key, invoice);
        try std.testing.expectEqualStrings(str(s, "publicKey"), &(try derive.pubHex(child)));
    }
}

test "childCounterSequence: keying on the parent alone is wrong, and the vector says so" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const seq = obj(v.root(), "childCounterSequence");
    const steps = seq.object.get("steps").?.array.items;
    const wrong = seq.object.get("wrongIfKeyedOnParentAlone").?.array.items;
    try std.testing.expectEqual(steps.len, wrong.len);

    // Replay with a deliberately broken key — parent only, ignoring the slot.
    var broken = derive.ChildCounters.init(a);
    defer broken.deinit();
    const root_cert_id = str(seq, "rootCertId");

    var diverged = false;
    for (steps, wrong) |s, w| {
        const got = try broken.next(root_cert_id, "", 1); // one bucket for everything
        try std.testing.expectEqual(@as(u64, @intCast(w.integer)), got);
        if (got != @as(u64, @intCast(int(s, "childIndex")))) diverged = true;
    }
    // If these two ever agree, the negative control has stopped controlling for
    // anything and the sequence needs a case that separates them again.
    try std.testing.expect(diverged);
}

test "ChildCounters: slots are independent and monotonic" {
    const a = std.testing.allocator;
    var c = derive.ChildCounters.init(a);
    defer c.deinit();

    try std.testing.expectEqual(@as(u64, 0), try c.next("p", "member", 6));
    try std.testing.expectEqual(@as(u64, 1), try c.next("p", "member", 6));
    try std.testing.expectEqual(@as(u64, 0), try c.next("p", "device", 6)); // other resource
    try std.testing.expectEqual(@as(u64, 0), try c.next("p", "member", 2)); // other flag
    try std.testing.expectEqual(@as(u64, 0), try c.next("q", "member", 6)); // other parent
    try std.testing.expectEqual(@as(u64, 2), try c.next("p", "member", 6));
}

// ── certId ───────────────────────────────────────────────────────────────────

const certid = @import("certid");

/// Build a Preimage from a vector case's JSON, preserving its (possibly
/// scrambled) field order so the encoder's own sort is what is under test.
fn preimageFrom(allocator: std.mem.Allocator, c: std.json.Value) !struct {
    p: certid.Preimage,
    fields: []certid.Field,
} {
    const f = obj(c, "fields").object;
    var list = try allocator.alloc(certid.Field, f.count());
    var it = f.iterator();
    var i: usize = 0;
    while (it.next()) |e| : (i += 1) {
        list[i] = .{ .key = e.key_ptr.*, .value = e.value_ptr.*.string };
    }
    return .{
        .p = .{
            .subject_public_key = str(c, "subjectPublicKey"),
            .certifier_public_key = str(c, "certifierPublicKey"),
            .type_name = str(c, "type"),
            .serial_number = str(c, "serialNumber"),
            .fields = list,
        },
        .fields = list,
    };
}

test "certIds: canonical JSON matches the oracle BYTE-FOR-BYTE, not just the hash" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const cases = arr(v.root(), "certIds");
    try std.testing.expect(cases.len >= 3);
    for (cases) |c| {
        const built = try preimageFrom(a, obj(c, "preimage"));
        defer a.free(built.fields);

        const json = try certid.canonicalJson(a, built.p);
        defer a.free(json);
        // The intermediate string is asserted first. A hash-only check passes on
        // an encoder that is accidentally right here and wrong in general.
        try std.testing.expectEqualStrings(str(c, "canonicalJson"), json);
        try std.testing.expectEqualStrings(str(c, "certId"), &certid.sha256Hex(json));
    }
}

test "certIds: computeCertId end to end" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    for (arr(v.root(), "certIds")) |c| {
        const built = try preimageFrom(a, obj(c, "preimage"));
        defer a.free(built.fields);
        const id = try certid.computeCertId(a, built.p);
        try std.testing.expectEqualStrings(str(c, "certId"), &id);
    }
}

test "certIds: scrambled input key order yields the same id" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    // The vector carries a case whose preimage keys are deliberately out of
    // order. It must land on the same id as the ordered one — that property is
    // what lets two implementations agree without agreeing on map iteration.
    const cases = arr(v.root(), "certIds");
    var ordered: ?[]const u8 = null;
    var scrambled: ?[]const u8 = null;
    for (cases) |c| {
        const label = str(c, "label");
        if (std.mem.eql(u8, label, "derived-child")) ordered = str(c, "certId");
        if (std.mem.indexOf(u8, label, "scrambled") != null) scrambled = str(c, "certId");
    }
    try std.testing.expect(ordered != null and scrambled != null);
    try std.testing.expectEqualStrings(ordered.?, scrambled.?);
}

test "certId: root and derived carry different field sets" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    // Guards the shape assumption: `fields` is a variable map, not a fixed
    // struct. A port that hardcoded the derived triple would pass two of three
    // vector cases and fail every root.
    for (arr(v.root(), "certIds")) |c| {
        const pre = obj(c, "preimage");
        const f = obj(pre, "fields").object;
        if (std.mem.eql(u8, str(pre, "type"), certid.type_root)) {
            try std.testing.expect(f.contains("email"));
        } else {
            try std.testing.expectEqualStrings(certid.type_derived, str(pre, "type"));
            try std.testing.expect(f.contains("resourceId"));
            try std.testing.expect(f.contains("domainFlag"));
            try std.testing.expect(f.contains("childIndex"));
        }
    }
}

test "certId: duplicate field keys are refused rather than silently resolved" {
    const a = std.testing.allocator;
    const dup = [_]certid.Field{
        .{ .key = "resourceId", .value = "inbox" },
        .{ .key = "resourceId", .value = "archive" },
    };
    try std.testing.expectError(certid.Error.DuplicateFieldKey, certid.canonicalJson(a, .{
        .subject_public_key = "02aa",
        .certifier_public_key = "02bb",
        .type_name = certid.type_derived,
        .serial_number = "00",
        .fields = &dup,
    }));
}

// ── string escaping ──────────────────────────────────────────────────────────
//
// The derivation vector reaches none of this: its certId values are hex, an
// email and a dotted type name — no quote, no backslash, no control character,
// no non-ASCII, no slash. An encoder can pass every case in it and still be
// wrong for any resourceId a human typed, which is the one field a fleet lets
// them name. These cases are generated from the SDK's own canonicalJson by
// vectors/gen-escaping-vector.mjs.

const GOLDEN_ESCAPING = @embedFile("golden_escaping");

fn hexToBytes(allocator: std.mem.Allocator, hex: []const u8) ![]u8 {
    const out = try allocator.alloc(u8, hex.len / 2);
    errdefer allocator.free(out);
    _ = try std.fmt.hexToBytes(out, hex);
    return out;
}

test "escaping: every generated case matches the oracle, as a value and as a key" {
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_ESCAPING, .{});
    defer parsed.deinit();

    const base = obj(parsed.value, "baseline");
    const subject = str(base, "subjectPublicKey");
    const certifier = str(base, "certifierPublicKey");
    const type_name = str(base, "type");
    const serial = str(base, "serialNumber");

    const cases = arr(parsed.value, "cases");
    try std.testing.expect(cases.len >= 40);

    var checked: usize = 0;
    var skipped: usize = 0;
    for (cases) |c| {
        // A lone surrogate has no well-formed UTF-8 encoding, so a Zig
        // []const u8 cannot carry one in. The divergence is unreachable from
        // this port rather than merely untested — skip, and count the skips so
        // a vector that silently became all-skips would show it.
        if (!obj(c, "representableInUtf8").bool) {
            skipped += 1;
            continue;
        }
        const raw = try hexToBytes(a, str(c, "inputUtf8Hex"));
        defer a.free(raw);

        const as_value = [_]certid.Field{.{ .key = "resourceId", .value = raw }};
        const got_value = try certid.canonicalJson(a, .{
            .subject_public_key = subject,
            .certifier_public_key = certifier,
            .type_name = type_name,
            .serial_number = serial,
            .fields = &as_value,
        });
        defer a.free(got_value);
        try std.testing.expectEqualStrings(str(c, "canonicalAsValue"), got_value);

        const as_key = [_]certid.Field{.{ .key = raw, .value = "v" }};
        const got_key = try certid.canonicalJson(a, .{
            .subject_public_key = subject,
            .certifier_public_key = certifier,
            .type_name = type_name,
            .serial_number = serial,
            .fields = &as_key,
        });
        defer a.free(got_key);
        try std.testing.expectEqualStrings(str(c, "canonicalAsKey"), got_key);
        checked += 1;
    }
    try std.testing.expect(checked >= 40);
    try std.testing.expectEqual(@as(usize, 2), skipped); // the two lone surrogates
}

test "escaping: the vector actually reaches the characters that matter" {
    // Guards the guard. If the generator ever stops emitting these, the suite
    // would keep passing while covering nothing — the failure mode this whole
    // section exists to close.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_ESCAPING, .{});
    defer parsed.deinit();

    var saw_quote = false;
    var saw_backslash = false;
    var saw_slash = false;
    var saw_control = false;
    var saw_non_ascii = false;
    for (arr(parsed.value, "cases")) |c| {
        const raw = try hexToBytes(a, str(c, "inputUtf8Hex"));
        defer a.free(raw);
        for (raw) |b| {
            if (b == '"') saw_quote = true;
            if (b == '\\') saw_backslash = true;
            if (b == '/') saw_slash = true;
            if (b < 0x20) saw_control = true;
            if (b >= 0x80) saw_non_ascii = true;
        }
    }
    try std.testing.expect(saw_quote);
    try std.testing.expect(saw_backslash);
    try std.testing.expect(saw_slash);
    try std.testing.expect(saw_control);
    try std.testing.expect(saw_non_ascii);
}

test "escaping: fields keys sort in UTF-16 code-unit order, not UTF-8 byte order" {
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_ESCAPING, .{});
    defer parsed.deinit();

    const base = obj(parsed.value, "baseline");
    const cases = arr(parsed.value, "sortCases");
    try std.testing.expect(cases.len >= 5);

    for (cases) |c| {
        const keys_hex = obj(c, "keysUtf8Hex").array.items;
        var fields = try a.alloc(certid.Field, keys_hex.len);
        defer {
            for (fields) |f| a.free(@constCast(f.key));
            a.free(fields);
        }
        for (keys_hex, 0..) |kh, i| {
            fields[i] = .{ .key = try hexToBytes(a, kh.string), .value = "v" };
        }

        const got = try certid.canonicalJson(a, .{
            .subject_public_key = str(base, "subjectPublicKey"),
            .certifier_public_key = str(base, "certifierPublicKey"),
            .type_name = str(base, "type"),
            .serial_number = str(base, "serialNumber"),
            .fields = fields,
        });
        defer a.free(got);
        try std.testing.expectEqualStrings(str(c, "canonical"), got);
    }
}

test "escaping: the sort cases actually contain a byte-vs-UTF16 disagreement" {
    // Guards the guard again. An emoji (U+1F600, UTF-8 f0...) against a
    // private-use char (U+E000, UTF-8 ee...) is the canonical disagreement: the
    // emoji sorts FIRST in UTF-16 and LAST by bytes. If no case carries such a
    // pair, this section proves nothing.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_ESCAPING, .{});
    defer parsed.deinit();

    var found = false;
    for (arr(parsed.value, "sortCases")) |c| {
        var has_astral = false;
        var has_high_bmp = false;
        for (obj(c, "keysUtf8Hex").array.items) |kh| {
            const raw = try hexToBytes(a, kh.string);
            defer a.free(raw);
            if (raw.len > 0 and raw[0] == 0xF0) has_astral = true;
            if (raw.len > 0 and (raw[0] == 0xEE or raw[0] == 0xEF)) has_high_bmp = true;
        }
        if (has_astral and has_high_bmp) found = true;
    }
    try std.testing.expect(found);
}

// ── end to end ───────────────────────────────────────────────────────────────

const identity = @import("identity");

test "end to end: the root certId is computable from (email, salt) alone" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const root = try identity.rootIdentity(a, str(universe, "rootEmail"), str(universe, "rootSalt"));

    // The vector's childCounterSequence names the root it was replayed against.
    const seq = obj(v.root(), "childCounterSequence");
    try std.testing.expectEqualStrings(str(seq, "rootCertId"), &root.cert_id);

    // And the certIds array carries the same root as a labelled case, with its
    // serialNumber — so both halves of the construction are pinned, not just
    // the id they happen to produce together.
    for (arr(v.root(), "certIds")) |c| {
        const pre = obj(c, "preimage");
        if (!std.mem.eql(u8, str(pre, "type"), certid.type_root)) continue;
        try std.testing.expectEqualStrings(str(pre, "serialNumber"), &root.serial_number);
        try std.testing.expectEqualStrings(str(pre, "subjectPublicKey"), &root.public_key_hex);
        try std.testing.expectEqualStrings(str(c, "certId"), &root.cert_id);
    }
}

test "end to end: every childCounterSequence step's certId is recomputed, not read" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const email = str(universe, "rootEmail");
    const salt = str(universe, "rootSalt");

    const seq = obj(v.root(), "childCounterSequence");
    const root_cert_id = str(seq, "rootCertId");
    const steps = seq.object.get("steps").?.array.items;

    var counters = derive.ChildCounters.init(a);
    defer counters.deinit();

    for (steps) |s| {
        const resource_id = str(s, "resourceId");
        const flag: u64 = @intCast(int(s, "domainFlag"));
        // Index comes from the allocator, everything else from derivation. The
        // only thing read from the vector is what we compare against.
        const index = try counters.next(root_cert_id, resource_id, flag);

        const child = try identity.deriveChildIdentity(a, email, salt, "root", resource_id, flag, index);
        defer child.deinit(a);

        try std.testing.expectEqualStrings(str(s, "invoiceNumber"), child.invoice_number);
        try std.testing.expectEqualStrings(str(s, "derivationPath"), child.derivation_path);
        try std.testing.expectEqualStrings(str(s, "publicKey"), &child.public_key_hex);
        try std.testing.expectEqualStrings(str(s, "certId"), &child.cert_id);
    }
}

test "end to end: a grandchild is certified by its PARENT, not by the root" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    // The vector's deepest path is root/inbox:2:0/sub:3:2. Building it proves
    // the certifier is the immediate parent — certifying against the root
    // instead produces a valid-looking id that no other implementation agrees
    // with, and every descendant inherits the fork.
    const universe = obj(v.root(), "universe");
    const email = str(universe, "rootEmail");
    const salt = str(universe, "rootSalt");

    const child = try identity.deriveChildIdentity(a, email, salt, "root/inbox:2:0", "sub", 3, 2);
    defer child.deinit(a);
    try std.testing.expectEqualStrings("root/inbox:2:0/sub:3:2", child.derivation_path);

    for (arr(v.root(), "derivationPaths")) |p| {
        if (!std.mem.eql(u8, str(p, "path"), "root/inbox:2:0/sub:3:2")) continue;
        try std.testing.expectEqualStrings(str(p, "pubHex"), &child.public_key_hex);
    }
}

// ── the fleet store ──────────────────────────────────────────────────────────

const Store = @import("store").Store;
const StoreError = @import("store").Error;
const GOLDEN_ROTATION = @embedFile("golden_rotation");

test "rotation: replaying the SDK's own trace reproduces every return value" {
    // Generated by driving the SDK's real MemoryKeyStore, so this asserts what
    // the semantics ARE rather than what I believe them to be. Ported tests
    // re-state a belief; a replayed trace does not.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_ROTATION, .{});
    defer parsed.deinit();

    var s = Store.initMemory(a);
    defer s.deinit();

    const steps = arr(parsed.value, "steps");
    try std.testing.expect(steps.len >= 15);

    for (steps) |st| {
        const op = str(st, "op");
        const p = str(st, "parent");
        const r = str(st, "resource");
        const f: u64 = @intCast(int(st, "flag"));
        const threw = obj(st, "threw").bool;

        if (std.mem.eql(u8, op, "allocate")) {
            const got = try s.allocateIndex(p, r, f);
            try std.testing.expectEqual(@as(u64, @intCast(int(st, "result"))), got);
        } else if (std.mem.eql(u8, op, "burn")) {
            const got = try s.burnSlot(p, r, f);
            try std.testing.expectEqual(@as(u64, @intCast(int(st, "result"))), got);
        } else if (std.mem.eql(u8, op, "restore")) {
            const n: u64 = @intCast(int(st, "nextIndex"));
            if (threw) {
                try std.testing.expectError(StoreError.CounterWouldRewind, s.restoreCounter(p, r, f, n));
            } else {
                try s.restoreCounter(p, r, f, n);
            }
        } else if (std.mem.eql(u8, op, "state")) {
            const got = try s.highWaterMark(p, r, f);
            try std.testing.expectEqual(@as(u64, @intCast(int(st, "result"))), got);
        } else {
            return error.UnknownOp;
        }
    }

    // End state, not just each step: the SDK's currentIndex equals the next
    // index it would allocate, which is what this store keeps as one counter.
    for (arr(parsed.value, "finalContexts")) |c| {
        const p = str(c, "parent");
        const r = str(c, "resource");
        const f: u64 = @intCast(int(c, "flag"));
        try std.testing.expectEqual(
            @as(u64, @intCast(int(c, "currentIndex"))),
            try s.highWaterMark(p, r, f),
        );
        try std.testing.expectEqual(
            @as(u64, @intCast(int(c, "nextAllocation"))),
            try s.allocateIndex(p, r, f),
        );
    }
}

test "rotation: the trace actually exercises burn, isolation and a refused rewind" {
    // Guards the guard: a trace that lost these would still pass above while
    // proving nothing about the semantics that matter.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_ROTATION, .{});
    defer parsed.deinit();

    var saw_burn = false;
    var saw_refused_restore = false;
    var saw_fresh_burn = false;
    var resources = std.StringHashMap(void).init(a);
    defer resources.deinit();

    for (arr(parsed.value, "steps")) |st| {
        const op = str(st, "op");
        if (std.mem.eql(u8, op, "burn")) saw_burn = true;
        if (std.mem.eql(u8, op, "restore") and obj(st, "threw").bool) saw_refused_restore = true;
        if (std.mem.eql(u8, op, "burn") and std.mem.eql(u8, str(st, "resource"), "fresh")) saw_fresh_burn = true;
        try resources.put(str(st, "resource"), {});
    }
    try std.testing.expect(saw_burn);
    try std.testing.expect(saw_refused_restore);
    try std.testing.expect(saw_fresh_burn); // burning an untouched context
    try std.testing.expect(resources.count() >= 3); // isolation is exercised
}

test "store: nodes round-trip and children come back in allocation order" {
    const a = std.testing.allocator;
    var s = Store.initMemory(a);
    defer s.deinit();

    try s.putNode(.{ .cert_id = "root", .parent_cert_id = null, .resource_id = "root", .domain_flag = 6, .child_index = 0, .label = "operator" });
    // Inserted out of order on purpose.
    try s.putNode(.{ .cert_id = "c2", .parent_cert_id = "root", .resource_id = "zone", .domain_flag = 6, .child_index = 2, .label = "south" });
    try s.putNode(.{ .cert_id = "c0", .parent_cert_id = "root", .resource_id = "zone", .domain_flag = 6, .child_index = 0, .label = "north" });

    try std.testing.expectEqual(@as(usize, 3), s.nodeCount());
    try std.testing.expectEqualStrings("operator", s.getNode("root").?.label);
    try std.testing.expect(s.getNode("nope") == null);
    try std.testing.expectError(StoreError.DuplicateNode, s.putNode(.{
        .cert_id = "c0", .parent_cert_id = "root", .resource_id = "zone",
        .domain_flag = 6, .child_index = 9, .label = "dup",
    }));

    const kids = try s.children("root");
    defer a.free(kids);
    try std.testing.expectEqual(@as(usize, 2), kids.len);
    try std.testing.expectEqualStrings("north", kids[0].label);
    try std.testing.expectEqualStrings("south", kids[1].label);
}

test "store: persists and reopens, and allocation resumes where it left off" {
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const path = try tmp.dir.realpathAlloc(a, ".");
    defer a.free(path);
    const db = try std.fs.path.join(a, &.{ path, "fleet.log" });
    defer a.free(db);

    {
        var s = try Store.open(a, db);
        defer s.deinit();
        try std.testing.expectEqual(@as(u64, 0), try s.allocateIndex("p", "member", 6));
        try std.testing.expectEqual(@as(u64, 1), try s.allocateIndex("p", "member", 6));
        try std.testing.expectEqual(@as(u64, 3), try s.burnSlot("p", "member", 6));
        try s.putNode(.{ .cert_id = "c0", .parent_cert_id = "p", .resource_id = "member", .domain_flag = 6, .child_index = 0, .label = "alice" });
    }
    {
        var s = try Store.open(a, db);
        defer s.deinit();
        // The burned index stays burned across a restart.
        try std.testing.expectEqual(@as(u64, 3), try s.highWaterMark("p", "member", 6));
        try std.testing.expectEqual(@as(u64, 3), try s.allocateIndex("p", "member", 6));
        try std.testing.expectEqualStrings("alice", s.getNode("c0").?.label);
    }
}

test "store: reopening repeatedly is idempotent" {
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const path = try tmp.dir.realpathAlloc(a, ".");
    defer a.free(path);
    const db = try std.fs.path.join(a, &.{ path, "fleet.log" });
    defer a.free(db);

    {
        var s = try Store.open(a, db);
        defer s.deinit();
        _ = try s.allocateIndex("p", "member", 6);
        _ = try s.burnSlot("p", "member", 6);
        try s.putNode(.{ .cert_id = "c0", .parent_cert_id = "p", .resource_id = "member", .domain_flag = 6, .child_index = 0, .label = "alice" });
    }
    var marks: [3]u64 = undefined;
    for (&marks) |*m| {
        var s = try Store.open(a, db);
        defer s.deinit();
        m.* = try s.highWaterMark("p", "member", 6);
        try std.testing.expectEqual(@as(usize, 1), s.nodeCount()); // not duplicated
    }
    try std.testing.expectEqual(marks[0], marks[1]);
    try std.testing.expectEqual(marks[1], marks[2]);
}

test "store: a torn final record is dropped, and the next append is clean" {
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const path = try tmp.dir.realpathAlloc(a, ".");
    defer a.free(path);
    const db = try std.fs.path.join(a, &.{ path, "fleet.log" });
    defer a.free(db);

    {
        var s = try Store.open(a, db);
        defer s.deinit();
        _ = try s.allocateIndex("p", "member", 6); // 0
        _ = try s.allocateIndex("p", "member", 6); // 1
    }
    // Simulate a process killed mid-append: a partial line with no terminator.
    {
        const f = try std.fs.cwd().openFile(db, .{ .mode = .read_write });
        defer f.close();
        try f.seekFromEnd(0);
        try f.writeAll("{\"op\":\"alloc\",\"p\":\"p\",\"r\":\"mem");
    }
    {
        var s = try Store.open(a, db);
        defer s.deinit();
        // The fragment contributed nothing, and the file was truncated back to
        // the last complete record — so the next allocation is 2, not garbage.
        try std.testing.expectEqual(@as(u64, 2), try s.allocateIndex("p", "member", 6));
    }
    {
        // And the log is readable again end to end after that append.
        var s = try Store.open(a, db);
        defer s.deinit();
        try std.testing.expectEqual(@as(u64, 3), try s.highWaterMark("p", "member", 6));
    }
}

test "store: contexts cannot be made to collide on one counter" {
    // The key is NUL-separated, so no cert id or resource id can be crafted to
    // land two different contexts in the same bucket.
    const a = std.testing.allocator;
    var s = Store.initMemory(a);
    defer s.deinit();

    try std.testing.expectEqual(@as(u64, 0), try s.allocateIndex("a|b", "c", 6));
    try std.testing.expectEqual(@as(u64, 0), try s.allocateIndex("a", "b|c", 6));
    try std.testing.expectEqual(@as(u64, 0), try s.allocateIndex("a", "b", 6));
    try std.testing.expectEqual(@as(u64, 1), try s.allocateIndex("a|b", "c", 6));
}

test "store: an unterminated but well-formed record is dropped — the newline is the commit" {
    // The nastier torn write. A fragment that fails to parse is caught by the
    // parser; a record whose bytes all landed but whose newline did not is
    // valid JSON, and only the terminator distinguishes it from a committed
    // one. Treating the newline as the commit marker is what makes a partial
    // append invisible rather than half-applied.
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const path = try tmp.dir.realpathAlloc(a, ".");
    defer a.free(path);
    const db = try std.fs.path.join(a, &.{ path, "fleet.log" });
    defer a.free(db);

    {
        var s = try Store.open(a, db);
        defer s.deinit();
        _ = try s.allocateIndex("p", "member", 6); // 0
    }
    {
        const f = try std.fs.cwd().openFile(db, .{ .mode = .read_write });
        defer f.close();
        try f.seekFromEnd(0);
        // Complete, parseable, and NOT newline-terminated.
        try f.writeAll("{\"op\":\"alloc\",\"p\":\"p\",\"r\":\"member\",\"f\":6,\"v\":99}");
    }
    {
        var s = try Store.open(a, db);
        defer s.deinit();
        // If the uncommitted record had been applied the mark would be 99.
        try std.testing.expectEqual(@as(u64, 1), try s.highWaterMark("p", "member", 6));
        try std.testing.expectEqual(@as(u64, 1), try s.allocateIndex("p", "member", 6));
    }
}

test "store: replay raises rather than sets, so record order cannot rewind a counter" {
    // A crash can interleave appends, and a log is not guaranteed to be sorted.
    // Replay takes the maximum, so a lower record arriving after a higher one
    // is ignored instead of undoing it. Written by hand precisely because the
    // store itself would never emit this order.
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const path = try tmp.dir.realpathAlloc(a, ".");
    defer a.free(path);
    const db = try std.fs.path.join(a, &.{ path, "fleet.log" });
    defer a.free(db);

    {
        const f = try std.fs.cwd().createFile(db, .{});
        defer f.close();
        try f.writeAll(
            \\{"op":"alloc","p":"p","r":"member","f":6,"v":7}
            \\{"op":"alloc","p":"p","r":"member","f":6,"v":3}
            \\{"op":"burn","p":"p","r":"member","f":6,"v":5}
            \\
        );
    }
    var s = try Store.open(a, db);
    defer s.deinit();
    try std.testing.expectEqual(@as(u64, 7), try s.highWaterMark("p", "member", 6));
    try std.testing.expectEqual(@as(u64, 7), try s.allocateIndex("p", "member", 6));
}

// ── capability certificates ──────────────────────────────────────────────────

const cert = @import("cert");
const GOLDEN_CERT = @embedFile("golden_cert");
const CAP_HEADER = @embedFile("cap_header");

fn parseU64(s: []const u8) !u64 {
    return std.fmt.parseInt(u64, s, 10);
}

test "cert: the 66-byte payload is byte-identical to the TypeScript plane's" {
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_CERT, .{});
    defer parsed.deinit();
    const v = parsed.value;

    const edge = try hexToBytes(a, str(obj(v, "device"), "publicKeyHex"));
    defer a.free(edge);
    const chan = try hexToBytes(a, str(v, "channelIdHex"));
    defer a.free(chan);

    const got = try cert.buildPayload(
        edge,
        chan,
        try parseU64(str(v, "expiryMs")),
        try parseU64(str(v, "validFromMs")),
    );
    var got_hex: [cert.payload_bytes * 2]u8 = undefined;
    _ = try std.fmt.bufPrint(&got_hex, "{x}", .{&got});
    try std.testing.expectEqualStrings(str(v, "certPayloadHex"), &got_hex);

    // And the BRC-108 binding hash over it.
    var ch_hex: [64]u8 = undefined;
    _ = try std.fmt.bufPrint(&ch_hex, "{x}", .{&cert.certHash(&got)});
    try std.testing.expectEqualStrings(str(v, "certHashHex"), &ch_hex);
}

test "cert: the 1 KB cell is byte-identical to the TypeScript plane's" {
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_CERT, .{});
    defer parsed.deinit();
    const v = parsed.value;

    const payload = try hexToBytes(a, str(v, "certPayloadHex"));
    defer a.free(payload);
    const anchor = try hexToBytes(a, str(v, "operatorPubKeyHex"));
    defer a.free(anchor);

    const cell = try cert.mintCell(
        cert.typeHash(cert.capability_v0_type_name),
        payload,
        anchor[0..16],
        try parseU64(str(v, "validFromMs")),
    );
    const got_hex = try a.alloc(u8, cert.cell_size * 2);
    defer a.free(got_hex);
    _ = try std.fmt.bufPrint(got_hex, "{x}", .{&cell});
    try std.testing.expectEqualStrings(str(v, "certCellHex"), got_hex);
}

test "cert: signatures interoperate both ways, even though the bytes differ" {
    // The honest form of M4's gate. Both planes are deterministic and neither
    // uses randomness, but they derive the ECDSA nonce differently — so the
    // signature bytes are NOT equal and cannot be. What must hold is that each
    // side verifies the other's, which is the only property the wire depends on.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_CERT, .{});
    defer parsed.deinit();
    const v = parsed.value;

    const universe = obj(v, "universe");
    const operator = try derive.derivePrivateKeyAtPath(
        str(universe, "rootEmail"),
        str(universe, "rootSalt"),
        "root",
    );
    const anchor = try hexToBytes(a, str(v, "operatorPubKeyHex"));
    defer a.free(anchor);
    // The plane signs as the root, so the anchor must be the root's own key.
    try std.testing.expectEqualStrings(str(v, "operatorPubKeyHex"), &(try derive.pubHex(operator)));

    const cell = try hexToBytes(a, str(v, "certCellHex"));
    defer a.free(cell);
    const ts_sig_bytes = try hexToBytes(a, str(v, "certSigHex"));
    defer a.free(ts_sig_bytes);
    var ts_sig: [64]u8 = undefined;
    @memcpy(&ts_sig, ts_sig_bytes);

    // Zig verifies what TypeScript signed.
    try std.testing.expect(try cert.verifyCell(anchor, cell, ts_sig));

    // Zig's own signature over the same cell verifies too...
    const zig_sig = try cert.signCell(operator, cell);
    try std.testing.expect(try cert.verifyCell(anchor, cell, zig_sig));

    // ...and is a DIFFERENT 64 bytes. Pinned so that if a future bsvz or Zig
    // release happens to converge on the same nonce scheme, this test says so
    // rather than silently passing on an assumption that stopped being true.
    try std.testing.expect(!std.mem.eql(u8, &ts_sig, &zig_sig));
}

test "cert: signatures are low-S, which bsvz does not give for free" {
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_CERT, .{});
    defer parsed.deinit();
    const v = parsed.value;

    const universe = obj(v, "universe");
    const operator = try derive.derivePrivateKeyAtPath(
        str(universe, "rootEmail"),
        str(universe, "rootSalt"),
        "root",
    );
    const half_n = [_]u8{
        0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
        0x5d, 0x57, 0x6e, 0x73, 0x57, 0xa4, 0x50, 0x1d, 0xdf, 0xe9, 0x2f, 0x46, 0x68, 0x1b, 0x20, 0xa0,
    };

    const anchor = try hexToBytes(a, str(v, "operatorPubKeyHex"));
    defer a.free(anchor);

    // Many cells, because bsvz's raw s is above half-n only about half the time
    // — a single sample would pass on an unnormalised signer by luck.
    var i: u64 = 0;
    while (i < 24) : (i += 1) {
        const cell = try cert.mintCell(
            cert.typeHash(cert.capability_v0_type_name),
            "payload",
            "0123456789abcdef",
            1_767_225_600_000 + i,
        );
        const sig = try cert.signCell(operator, &cell);
        try std.testing.expect(std.mem.order(u8, sig[32..64], &half_n) != .gt);
        // Normalising must not have broken it.
        try std.testing.expect(try cert.verifyCell(anchor, &cell, sig));
    }
}

test "cert: payload offsets track cell_capability.h" {
    // The seam's other half. cert.zig mirrors these constants; this reads the
    // firmware header and checks them, so a layout change fails here rather
    // than on a board.
    const constant = struct {
        fn get(name: []const u8) !u64 {
            var it = std.mem.tokenizeAny(u8, CAP_HEADER, "\n");
            while (it.next()) |line| {
                const t = std.mem.trim(u8, line, " \t\r");
                if (!std.mem.startsWith(u8, t, "#define ")) continue;
                var parts = std.mem.tokenizeAny(u8, t[8..], " \t");
                const key = parts.next() orelse continue;
                if (!std.mem.eql(u8, key, name)) continue;
                var val = parts.next() orelse continue;
                if (std.mem.endsWith(u8, val, "u")) val = val[0 .. val.len - 1];
                if (std.mem.startsWith(u8, val, "0x")) return std.fmt.parseInt(u64, val[2..], 16);
                return std.fmt.parseInt(u64, val, 10);
            }
            return error.NotFound;
        }
    };
    try std.testing.expectEqual(@as(u64, cert.payload_bytes), try constant.get("CM_CAP_PAYLOAD_BYTES"));
    try std.testing.expectEqual(@as(u64, cert.off_edge_pubkey), try constant.get("CM_CAP_OFF_EDGE_PUBKEY"));
    try std.testing.expectEqual(@as(u64, cert.off_channel_id), try constant.get("CM_CAP_OFF_CHANNEL_ID"));
    try std.testing.expectEqual(@as(u64, cert.off_expiry_ms), try constant.get("CM_CAP_OFF_EXPIRY_MS"));
    try std.testing.expectEqual(@as(u64, cert.off_route_type), try constant.get("CM_CAP_OFF_ROUTE_TYPE"));
    try std.testing.expectEqual(@as(u64, cert.off_valid_from_ms), try constant.get("CM_CAP_OFF_VALID_FROM_MS"));
    try std.testing.expectEqual(@as(u64, cert.route_fwd_v1), try constant.get("CM_CAP_ROUTE_FWD_V1"));
}

test "cert: a real expiry pins the field's byte order" {
    // The default no-expiry value is UINT64_MAX — eight 0xff bytes, identical in
    // either endianness — so a vector carrying only that cannot catch a byte
    // order mistake. This case has distinguishable bytes in every octet.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_CERT, .{});
    defer parsed.deinit();
    const v = parsed.value;
    const c = obj(v, "realExpiryCase");

    const edge = try hexToBytes(a, str(c, "devicePublicKeyHex"));
    defer a.free(edge);
    const chan = try hexToBytes(a, str(c, "channelIdHex"));
    defer a.free(chan);

    const expiry = try parseU64(str(c, "expiryMs"));
    try std.testing.expect(expiry != std.math.maxInt(u64)); // guard the guard

    const got = try cert.buildPayload(edge, chan, expiry, try parseU64(str(v, "validFromMs")));
    var got_hex: [cert.payload_bytes * 2]u8 = undefined;
    _ = try std.fmt.bufPrint(&got_hex, "{x}", .{&got});
    try std.testing.expectEqualStrings(str(c, "certPayloadHex"), &got_hex);

    const anchor = try hexToBytes(a, str(v, "operatorPubKeyHex"));
    defer a.free(anchor);
    const cell = try cert.mintCell(
        cert.typeHash(cert.capability_v0_type_name),
        &got,
        anchor[0..16],
        try parseU64(str(v, "validFromMs")),
    );
    const cell_hex = try a.alloc(u8, cert.cell_size * 2);
    defer a.free(cell_hex);
    _ = try std.fmt.bufPrint(cell_hex, "{x}", .{&cell});
    try std.testing.expectEqualStrings(str(c, "certCellHex"), cell_hex);
}

test "hardware parity: the Zig plane derives what the TypeScript plane flashed" {
    // The demo fleet the C6 boards carry an anchor for. Both planes must agree
    // on the operator key, the paths, the device key and the channel — and the
    // channel is the device certId's first 16 bytes, so matching it also proves
    // the canonical-JSON certId agrees. Pinned here so parity is checked in CI
    // rather than noticed by eye during a hardware run.
    const a = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(std.json.Value, a, GOLDEN_CERT, .{});
    defer parsed.deinit();
    const c = obj(parsed.value, "hardwareParityCase");

    const email = str(c, "rootEmail");
    const salt = str(c, "rootSalt");

    const operator = try derive.derivePrivateKeyAtPath(email, salt, "root");
    try std.testing.expectEqualStrings(str(c, "operatorPubKeyHex"), &(try derive.pubHex(operator)));

    const zone = try identity.deriveChildIdentity(a, email, salt, "root", "zone", 6, 0);
    defer zone.deinit(a);
    try std.testing.expectEqualStrings(str(c, "zoneDerivationPath"), zone.derivation_path);

    const unit = try identity.deriveChildIdentity(a, email, salt, zone.derivation_path, "device", 6, 0);
    defer unit.deinit(a);
    try std.testing.expectEqualStrings(str(c, "deviceDerivationPath"), unit.derivation_path);
    try std.testing.expectEqualStrings(str(c, "devicePublicKeyHex"), &unit.public_key_hex);
    try std.testing.expectEqualStrings(str(c, "deviceCertId"), &unit.cert_id);

    const channel = try cert.channelIdFor(&unit.cert_id);
    var chan_hex: [32]u8 = undefined;
    _ = try std.fmt.bufPrint(&chan_hex, "{x}", .{&channel});
    try std.testing.expectEqualStrings(str(c, "channelIdHex"), &chan_hex);
}
