//! Cross-implementation conformance: this Zig port against the SDK's oracle.
//!
//! The vector is GENERATED by `plexus-sdk-ts/tools/gen-derivation-vector.mjs` and
//! vendored here verbatim. Its provenance and sha256 are in `vectors/README.md`.
//! Nothing in this file invents an expected value — every assertion reads from
//! the vector, so a drifting port fails rather than a drifting test passing.

const std = @import("std");
const derive = @import("derive");

const GOLDEN = @embedFile("golden");

const Vector = struct {
    parsed: std.json.Parsed(std.json.Value),

    fn load(allocator: std.mem.Allocator) !Vector {
        return .{ .parsed = try std.json.parseFromSlice(
            std.json.Value,
            allocator,
            GOLDEN,
            .{},
        ) };
    }
    fn deinit(self: *Vector) void {
        self.parsed.deinit();
    }
    fn root(self: Vector) std.json.Value {
        return self.parsed.value;
    }
};

fn obj(v: std.json.Value, key: []const u8) std.json.Value {
    return v.object.get(key).?;
}
fn str(v: std.json.Value, key: []const u8) []const u8 {
    return obj(v, key).string;
}
fn int(v: std.json.Value, key: []const u8) i64 {
    return obj(v, key).integer;
}
fn arr(v: std.json.Value, key: []const u8) []std.json.Value {
    return obj(v, key).array.items;
}

// ── constants ────────────────────────────────────────────────────────────────

test "constants: PBKDF2 parameters match the vector" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const p = obj(obj(v.root(), "constants"), "pbkdf2");
    try std.testing.expectEqual(@as(i64, derive.pbkdf2_iterations), int(p, "iterations"));
    try std.testing.expectEqual(@as(i64, @intCast(derive.pbkdf2_key_length)), int(p, "keyLength"));
    try std.testing.expectEqualStrings("sha512", str(p, "digest"));
}

// ── root keys ────────────────────────────────────────────────────────────────

test "rootKeys: every (email, salt) pair reproduces the oracle's root" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const cases = arr(v.root(), "rootKeys");
    try std.testing.expect(cases.len >= 3);
    for (cases) |c| {
        const key = try derive.deriveRootKey(str(c, "email"), str(c, "salt"));
        try std.testing.expectEqualStrings(str(c, "privHex"), &derive.privHex(key));
        try std.testing.expectEqualStrings(str(c, "pubHex"), &(try derive.pubHex(key)));
    }
}

test "rootKeys: a different salt yields a different universe" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();
    const cases = arr(v.root(), "rootKeys");
    // Same email, different salt — the vector's first two cases.
    try std.testing.expectEqualStrings(str(cases[0], "email"), str(cases[1], "email"));
    try std.testing.expect(!std.mem.eql(u8, str(cases[0], "privHex"), str(cases[1], "privHex")));
}

// ── invoice numbers ──────────────────────────────────────────────────────────

test "invoiceNumbers: every case renders exactly, including the colon collision" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    var saw_colon_case = false;
    for (arr(v.root(), "invoiceNumbers")) |c| {
        const resource_id = str(c, "resourceId");
        const flag: u64 = @intCast(int(c, "domainFlag"));
        const index: u64 = @intCast(int(c, "childIndex"));

        const got = try derive.buildInvoiceNumber(a, resource_id, flag, index);
        defer a.free(got);
        try std.testing.expectEqualStrings(str(c, "invoiceNumber"), got);

        // The cert-field encoding is HEX and unpadded, unlike the decimal the
        // invoice uses. Both are pinned, because confusing them is silent.
        const enc = try derive.encodeDomainFlag(a, flag);
        defer a.free(enc);
        try std.testing.expectEqualStrings(str(c, "domainFlagCertEncoding"), enc);

        if (std.mem.indexOfScalar(u8, resource_id, ':') != null) saw_colon_case = true;
    }
    // The vector deliberately carries a resourceId containing a colon. If it
    // ever stops doing so, this port's reproduction of that ambiguity is no
    // longer covered and the assumption should be revisited.
    try std.testing.expect(saw_colon_case);
}

test "invoiceNumbers: invalid inputs are refused" {
    const a = std.testing.allocator;
    try std.testing.expectError(
        derive.Error.EmptyResourceId,
        derive.buildInvoiceNumber(a, "", 2, 0),
    );
    try std.testing.expectError(
        derive.Error.InvalidDomainFlag,
        derive.buildInvoiceNumber(a, "inbox", 0, 0),
    );
    try std.testing.expectError(
        derive.Error.InvalidDomainFlag,
        derive.buildInvoiceNumber(a, "inbox", 0x1_0000_0000, 0),
    );
}

// ── plexus-kdf-v1 ────────────────────────────────────────────────────────────

test "plexus-kdf-v1: every case matches the oracle" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const root_key = try derive.deriveRootKey(
        str(universe, "rootEmail"),
        str(universe, "rootSalt"),
    );

    const v1 = obj(obj(v.root(), "kdf"), "plexus-kdf-v1");
    const cases = v1.object.get("cases").?.array.items;
    try std.testing.expect(cases.len >= 2);
    for (cases) |c| {
        const child = try derive.deriveChildV1(root_key, str(c, "invoiceNumber"));
        try std.testing.expectEqualStrings(str(c, "privHex"), &derive.privHex(child));
        try std.testing.expectEqualStrings(str(c, "pubHex"), &(try derive.pubHex(child)));
    }
}

test "plexus-kdf-v1: self-derivation, not an external counterparty" {
    // Guards the exact confusion with host.deriveLeaf: derive the same invoice
    // against a DIFFERENT counterparty and it must not produce the vector's key.
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const root_key = try derive.deriveRootKey(
        str(universe, "rootEmail"),
        str(universe, "rootSalt"),
    );
    const cases = obj(obj(v.root(), "kdf"), "plexus-kdf-v1").object.get("cases").?.array.items;
    const invoice = str(cases[0], "invoiceNumber");

    const stranger = try derive.deriveRootKey("stranger@example.test", "other-salt");
    const wrong = try root_key.deriveChild(try stranger.publicKey(), invoice);
    try std.testing.expect(!std.mem.eql(u8, str(cases[0], "privHex"), &derive.privHex(wrong)));
}

// ── paths ────────────────────────────────────────────────────────────────────

test "derivationPaths: every path walks to the oracle's key" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const email = str(universe, "rootEmail");
    const salt = str(universe, "rootSalt");

    const paths = arr(v.root(), "derivationPaths");
    try std.testing.expect(paths.len >= 3);
    for (paths) |p| {
        const key = try derive.derivePrivateKeyAtPath(email, salt, str(p, "path"));
        try std.testing.expectEqualStrings(str(p, "privHex"), &derive.privHex(key));
        try std.testing.expectEqualStrings(str(p, "pubHex"), &(try derive.pubHex(key)));
    }
}

test "derivationPaths: malformed paths are refused" {
    try std.testing.expectError(
        derive.Error.PathMustBeginAtRoot,
        derive.derivePrivateKeyAtPath("e", "s", "inbox:2:0"),
    );
    try std.testing.expectError(
        derive.Error.EmptyPathSegment,
        derive.derivePrivateKeyAtPath("e", "s", "root//inbox:2:0"),
    );
    try std.testing.expectError(
        derive.Error.EmptyPath,
        derive.derivePrivateKeyAtPath("e", "s", ""),
    );
}

// ── child counter sequence ───────────────────────────────────────────────────

test "childCounterSequence: replaying the oracle's calls reproduces every index and key" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const universe = obj(v.root(), "universe");
    const email = str(universe, "rootEmail");
    const salt = str(universe, "rootSalt");
    const root_key = try derive.deriveRootKey(email, salt);

    const seq = obj(v.root(), "childCounterSequence");
    const root_cert_id = str(seq, "rootCertId");
    const steps = seq.object.get("steps").?.array.items;
    try std.testing.expect(steps.len >= 5);

    var counters = derive.ChildCounters.init(a);
    defer counters.deinit();

    for (steps) |s| {
        const resource_id = str(s, "resourceId");
        const flag: u64 = @intCast(int(s, "domainFlag"));

        // The index is ALLOCATED, not read from the vector — that is the point.
        const index = try counters.next(root_cert_id, resource_id, flag);
        try std.testing.expectEqual(@as(u64, @intCast(int(s, "childIndex"))), index);

        const invoice = try derive.buildInvoiceNumber(a, resource_id, flag, index);
        defer a.free(invoice);
        try std.testing.expectEqualStrings(str(s, "invoiceNumber"), invoice);

        const path = try std.fmt.allocPrint(a, "root/{s}", .{invoice});
        defer a.free(path);
        try std.testing.expectEqualStrings(str(s, "derivationPath"), path);

        const child = try derive.deriveChildV1(root_key, invoice);
        try std.testing.expectEqualStrings(str(s, "publicKey"), &(try derive.pubHex(child)));
    }
}

test "childCounterSequence: keying on the parent alone is wrong, and the vector says so" {
    const a = std.testing.allocator;
    var v = try Vector.load(a);
    defer v.deinit();

    const seq = obj(v.root(), "childCounterSequence");
    const steps = seq.object.get("steps").?.array.items;
    const wrong = seq.object.get("wrongIfKeyedOnParentAlone").?.array.items;
    try std.testing.expectEqual(steps.len, wrong.len);

    // Replay with a deliberately broken key — parent only, ignoring the slot.
    var broken = derive.ChildCounters.init(a);
    defer broken.deinit();
    const root_cert_id = str(seq, "rootCertId");

    var diverged = false;
    for (steps, wrong) |s, w| {
        const got = try broken.next(root_cert_id, "", 1); // one bucket for everything
        try std.testing.expectEqual(@as(u64, @intCast(w.integer)), got);
        if (got != @as(u64, @intCast(int(s, "childIndex")))) diverged = true;
    }
    // If these two ever agree, the negative control has stopped controlling for
    // anything and the sequence needs a case that separates them again.
    try std.testing.expect(diverged);
}

test "ChildCounters: slots are independent and monotonic" {
    const a = std.testing.allocator;
    var c = derive.ChildCounters.init(a);
    defer c.deinit();

    try std.testing.expectEqual(@as(u64, 0), try c.next("p", "member", 6));
    try std.testing.expectEqual(@as(u64, 1), try c.next("p", "member", 6));
    try std.testing.expectEqual(@as(u64, 0), try c.next("p", "device", 6)); // other resource
    try std.testing.expectEqual(@as(u64, 0), try c.next("p", "member", 2)); // other flag
    try std.testing.expectEqual(@as(u64, 0), try c.next("q", "member", 6)); // other parent
    try std.testing.expectEqual(@as(u64, 2), try c.next("p", "member", 6));
}
