const std = @import("std");
const Sha256 = std.crypto.hash.sha2.Sha256;
const wire = @import("cell_wire.zig");

pub const table_max: usize = 4;
/// No domain policy configured: accept a cert in any domain, still bind exactly.
/// 0xffffffff is outside every allocated band, so it cannot collide with a real
/// flag. It is set EXPLICITLY by cm_cap_table_init rather than falling out of a
/// memset, because "whatever zero happens to mean" is not a security decision.
pub const domain_any: u32 = 0xffff_ffff;
pub const payload_bytes: usize = 66;
pub const route_fwd_v1: u8 = 0x01;
const no_expiry = std.math.maxInt(u64);

const ok: c_int = 0;
const err_bad_payload: c_int = -1;
const err_expired: c_int = -2;
const err_table_full: c_int = -3;
const err_wrong_domain: c_int = -4;

pub const CapEntry = extern struct {
    valid: bool,
    channel_id: [16]u8,
    edge_pubkey: [33]u8,
    route_type: u8,
    expiry_ms: u64,
    valid_from_ms: u64,
    cert_hash: [32]u8,
    /// The domain this cert was ISSUED in — read from the cert cell's own
    /// header at bytes 24-27, not from the 66-byte payload, which has no spare
    /// room. This is the `expected_flag` half of OP_CHECKDOMAINFLAG.
    domain_flag: u32,
};

pub const CapTable = extern struct {
    entries: [table_max]CapEntry,
    /// Which domain this DEVICE will install certs for. `domain_any` accepts
    /// all of them (still binding each cert to its own). A provisioned device
    /// narrows this to the domain it belongs to, so a cert the operator
    /// legitimately signed for a DIFFERENT domain is refused here rather than
    /// becoming usable authority on the wrong side of the namespace.
    required_domain_flag: u32,
};

pub export fn cm_cap_table_init(maybe_t: ?*CapTable) callconv(.c) void {
    const t = maybe_t orelse return;
    t.* = std.mem.zeroes(CapTable);
    // NOT left as the memset's 0: zero is a real, allocatable domain flag
    // (it is what every undeclared cell carries today), so leaving it would
    // silently mean "accept only undeclared" — a policy nobody chose.
    t.required_domain_flag = domain_any;
}

pub export fn cm_cap_set_domain(maybe_t: ?*CapTable, domain_flag: u32) callconv(.c) void {
    const t = maybe_t orelse return;
    t.required_domain_flag = domain_flag;
}

pub export fn cm_cap_get_domain(maybe_t: ?*const CapTable) callconv(.c) u32 {
    const t = maybe_t orelse return domain_any;
    return t.required_domain_flag;
}

/// The OP_CHECKDOMAINFLAG predicate, in native code.
///
/// Deliberately its own function rather than an inline `==`: it is the thing a
/// differential test can point at, and the golden vector in
/// `test/vectors/domainflag_vectors.h` is generated by running the REAL opcode
/// in the embedded WASM engine over the same inputs. If these two ever
/// disagree, the test fails and this is the side that is wrong.
pub export fn cm_domain_flag_matches(actual: u32, expected: u32) callconv(.c) bool {
    return actual == expected;
}

pub export fn cm_cap_install(
    maybe_t: ?*CapTable,
    maybe_payload: ?[*]const u8,
    payload_len: usize,
    now_ms: u64,
    domain_flag: u32,
) callconv(.c) c_int {
    const t = maybe_t orelse return err_bad_payload;
    const payload = maybe_payload orelse return err_bad_payload;
    if (payload_len < payload_bytes) return err_bad_payload;

    // Device policy, checked BEFORE anything is written. A cert the operator
    // genuinely signed, for a domain this device is not in, is still refused.
    if (t.required_domain_flag != domain_any and
        !cm_domain_flag_matches(domain_flag, t.required_domain_flag))
    {
        return err_wrong_domain;
    }

    const expiry_ms = wire.readU64(payload[49..][0..8]);
    const route_type = payload[57];
    const valid_from_ms = wire.readU64(payload[58..][0..8]);

    if (expiry_ms != no_expiry and expiry_ms <= now_ms) return err_expired;

    var cert_hash: [32]u8 = undefined;
    Sha256.hash(payload[0..payload_bytes], cert_hash[0..], .{});

    var free_slot: ?usize = null;
    for (&t.entries, 0..) |*e, i| {
        if (!e.valid or (e.expiry_ms != no_expiry and e.expiry_ms <= now_ms)) {
            if (free_slot == null) free_slot = i;
            continue;
        }
        if (std.mem.eql(u8, e.channel_id[0..], payload[33..49]) and
            e.route_type == route_type and
            cm_domain_flag_matches(e.domain_flag, domain_flag))
        {
            // Renewal of the SAME grant. A cert for the same channel in a
            // different domain is a different grant and must not overwrite
            // this one — it takes a slot of its own, or fails as table-full.
            @memcpy(e.edge_pubkey[0..], payload[0..33]);
            @memcpy(e.cert_hash[0..], cert_hash[0..]);
            e.expiry_ms = expiry_ms;
            e.valid_from_ms = valid_from_ms;
            return ok;
        }
    }

    const idx = free_slot orelse return err_table_full;
    var e = &t.entries[idx];
    e.valid = true;
    e.route_type = route_type;
    e.expiry_ms = expiry_ms;
    e.valid_from_ms = valid_from_ms;
    e.domain_flag = domain_flag;
    @memcpy(e.channel_id[0..], payload[33..49]);
    @memcpy(e.edge_pubkey[0..], payload[0..33]);
    @memcpy(e.cert_hash[0..], cert_hash[0..]);
    return ok;
}

fn findEntry(
    maybe_t: ?*CapTable,
    maybe_channel_id: ?[*]const u8,
    route_type: u8,
    now_ms: u64,
    domain_flag: u32,
) ?*CapEntry {
    const t = maybe_t orelse return null;
    const channel_id = maybe_channel_id orelse return null;
    for (&t.entries) |*e| {
        if (!e.valid) continue;
        if (e.expiry_ms != no_expiry and e.expiry_ms <= now_ms) {
            e.valid = false;
            continue;
        }
        if (e.route_type != route_type) continue;
        // THE ENFORCEMENT. A cell declaring domain X cannot borrow authority
        // that was issued for domain Y — the entry simply is not found, and
        // the caller's existing no-cert path drops the cell. Fail-closed by
        // reusing a refusal that already exists rather than adding a new one.
        if (!cm_domain_flag_matches(e.domain_flag, domain_flag)) continue;
        if (!std.mem.eql(u8, e.channel_id[0..], channel_id[0..16])) continue;
        return e;
    }
    return null;
}

pub export fn cm_cap_lookup(
    maybe_t: ?*CapTable,
    maybe_channel_id: ?[*]const u8,
    route_type: u8,
    now_ms: u64,
    domain_flag: u32,
) callconv(.c) ?[*]const u8 {
    const e = findEntry(maybe_t, maybe_channel_id, route_type, now_ms, domain_flag) orelse return null;
    return @ptrCast(&e.edge_pubkey);
}

pub export fn cm_cap_cert_hash(
    maybe_t: ?*CapTable,
    maybe_channel_id: ?[*]const u8,
    route_type: u8,
    now_ms: u64,
    domain_flag: u32,
) callconv(.c) ?[*]const u8 {
    const e = findEntry(maybe_t, maybe_channel_id, route_type, now_ms, domain_flag) orelse return null;
    return @ptrCast(&e.cert_hash);
}

pub export fn cm_cap_evict_expired(maybe_t: ?*CapTable, now_ms: u64) callconv(.c) void {
    const t = maybe_t orelse return;
    for (&t.entries) |*e| {
        if (e.valid and e.expiry_ms != no_expiry and e.expiry_ms <= now_ms) {
            e.valid = false;
        }
    }
}

pub export fn cm_cap_valid_count(maybe_t: ?*const CapTable, now_ms: u64) callconv(.c) c_int {
    const t = maybe_t orelse return 0;
    var n: c_int = 0;
    for (&t.entries) |*e| {
        if (e.valid and (e.expiry_ms == no_expiry or e.expiry_ms > now_ms)) n += 1;
    }
    return n;
}
